### ISSUE TITLE
Melee Fox voice doesn't work

### ISSUE THREAD

**Issue by CorBond57** [RetroGamer732/Smash-3DS-Custom-Content-Project#2]
Seems according to nus3bank.py it has an incorrect header, and all fox's voice effects are muted when you use it.

**Comment by RetroGamer732** [comment]
It worked for me, I'll try reuploading it. Also, there isn't a voice on his Rapid Jab/Tilts because there weren't in Melee. The sounds are on His Smashes, Up and Side B, and Full Jump, and Damage/Death sounds as well as Taunts and Win Quotes.

**Comment by CorBond57** [comment]
This should be fixed now. feel free to close it.

**Comment by CorBond57** [comment]
This should be fixed now.
